export const siteUrl = "https://vayia-vs-portfolio.vercel.app";

export const curatedImageOrder = [
  "ist8-street.jpg",
  "rome2-archit.png",
  "greece1-landsc.png",
  "skg1-street-int.jpg",
  "ist1-archit-int.png",
  "rome7-street.png",
  "greece3-street.png",
  "ist15-landsc.jpg",
  "rome8-archit-int.png",
  "skg2-street.png",
  "ist10-street.png",
  "rome4-int.png",
  "greece2-landsc.png",
  "ist7-archit.png",
  "rome1-street.png",
  "greece5-street.png",
  "ist9-archit.png",
  "skg3-street.png",
  "rome3-archit-int.png",
  "ist4-street.jpg",
  "greece4-street.png",
  "rome6-archit.png",
  "ist11-street.png",
  "ist2-street.jpg",
  "ist14-street.png",
  "ist5-street.jpg",
  "ist12-street.png",
  "ist3-street.jpg",
  "ist13-street.png",
  "ist6-street.jpg",
  "ist7-street.jpg",
];

export const featuredCategoryOrder: Record<string, string[]> = {
  street: [
    "ist8-street.jpg",
    "rome7-street.png",
    "greece3-street.png",
    "skg1-street-int.jpg",
    "ist10-street.png",
    "greece4-street.png",
    "rome1-street.png",
    "ist4-street.jpg",
  ],
  landsc: [
    "greece1-landsc.png",
    "ist15-landsc.jpg",
    "greece2-landsc.png",
    "greece5-street.png",
  ],
  archit: [
    "rome2-archit.png",
    "ist1-archit-int.png",
    "rome8-archit-int.png",
    "ist7-archit.png",
    "ist9-archit.png",
    "rome3-archit-int.png",
    "rome6-archit.png",
  ],
  int: [
    "rome4-int.png",
    "rome8-archit-int.png",
    "rome3-archit-int.png",
    "ist1-archit-int.png",
    "skg1-street-int.jpg",
  ],
};

export const homeContent = {
  en: {
    nav: [
      { label: "Gallery", target: "gallery" },
      { label: "About", target: "about" },
      { label: "Contact", target: "contact" },
    ],
    heroTitle1: "Capturing",
    heroTitle2: "Moments",
    heroTitle3: "in Time",
    heroText:
      "Street, portrait, and atmospheric photography shaped by quiet observation, natural light, and real moments.",
    viewGallery: "View Gallery",
    contactButton: "Get in Touch",
    galleryTitle: "My Collections",
    showMore: "more...",
    aboutTitle1: "The Art",
    aboutTitle2: "of Seeing",
    aboutKicker: "About the work",
    aboutText: [
      "I photograph the city as it unfolds: small gestures, passing light, and the quiet tension between people and place.",
      "My work moves between street photography, portraiture, architecture, and landscapes, always guided by atmosphere rather than performance.",
      "I am drawn to images that feel intimate and unforced. Even when the frame is simple, I want it to carry rhythm, stillness, and a sense of presence.",
      "Based in Athens and available for selected collaborations.",
    ],
    contactTitle1: "Let's Work",
    contactTitle2: "Together",
    contactKicker: "Get in touch",
    contactText:
      "If you have a portrait session, a brand idea, or a visual project in mind, send me a message and we can shape it together.",
    contactEmail: "vayiavs95@gmail.com",
    formName: "Name",
    formNamePlaceholder: "Your name",
    formEmail: "Email",
    formEmailPlaceholder: "your@email.com",
    formInquiryType: "Inquiry Type",
    formInquiryOptions: ["Portrait session", "Brand or product", "Creative project"],
    formTimeframe: "Timeframe",
    formTimeframeOptions: ["Flexible", "This month", "Next 1-2 months"],
    formBudget: "Budget",
    formBudgetOptions: ["Under €150", "€150-€300", "€300+"],
    formMessage: "Message",
    formMessagePlaceholder: "Tell me what you have in mind...",
    contactCTA: "Send Message",
    contactSending: "Sending...",
    contactSuccess: "Your message has been sent.",
    contactError: "Something went wrong. Please try again.",
    servicesKicker: "Work with me",
    servicesTitle: "",
    servicesLead:
      "From portraits and brands to more atmospheric creative sessions, each collaboration is shaped around mood, clarity, and the feeling the images should leave behind.",
    servicesHeading: "Ways We Can Work Together",
    services: [
      {
        title: "Portraits",
        text: "Editorial-feeling portraits, couples sessions, and quiet personal photographs with a natural, relaxed direction.",
      },
      {
        title: "Brand & Product",
        text: "Clean, atmospheric imagery for small businesses, personal brands, online shops, and visual campaigns.",
      },
      {
        title: "Creative Sessions",
        text: "Collaborative shoots and visual storytelling sessions built around mood, location, and the identity of the project.",
      },
    ],
    offersTitle: "Booking Guide",
    offers: [
      {
        label: "Portrait Session",
        price: "from €120",
        meta: "60-90 minutes",
      },
      {
        label: "Brand Imagery",
        price: "from €180",
        meta: "small business / product",
      },
      {
        label: "Creative Project",
        price: "custom quote",
        meta: "concept-based",
      },
    ],
    processTitle: "How it works",
    process: [
      "You send the idea, mood, or need.",
      "We decide on direction, timing, and location.",
      "You receive a clear quote and a simple plan.",
      "The final gallery is delivered by email.",
    ],
    inquire: "Inquire",
    portraitCaption: "Quiet moments, honest presence",
    contactMeta: "Athens-based • selected collaborations • replies by email",
    footerTagline: "Street • Portrait • Atmosphere",
    footerLocation: "Athens, Greece",
  },
  gr: {
    nav: [
      { label: "Συλλογές", target: "gallery" },
      { label: "Σχετικά με εμένα", target: "about" },
      { label: "Επικοινωνία", target: "contact" },
    ],
    heroTitle1: "Στιγμές",
    heroTitle2: "που",
    heroTitle3: "μένουν",
    heroText:
      "Φωτογραφίες δρόμου, πορτρέτα και εικόνες ατμόσφαιρας με έμφαση στο φως, την παρατήρηση και τις αληθινές στιγμές.",
    viewGallery: "Περιήγηση",
    contactButton: "Επικοινωνία",
    galleryTitle: "Οι Συλλογές μου",
    showMore: "Περισσοτερα",
    aboutTitle1: "Πίσω",
    aboutTitle2: "από τον φακό",
    aboutKicker: "Σχετικά με εμένα",
    aboutText: [
      "Φωτογραφίζω την πόλη όπως αποκαλύπτεται: μικρές κινήσεις, περαστικό φως και τη σχέση ανάμεσα στους ανθρώπους και τον χώρο.",
      "Η δουλειά μου κινείται ανάμεσα στη φωτογραφία δρόμου, τα πορτρέτα, την αρχιτεκτονική και τα τοπία, με βάση πάντα την ατμόσφαιρα και όχι τη σκηνοθεσία.",
      "Με ενδιαφέρουν οι εικόνες που νιώθουν ήσυχες αλλά παρούσες. Ακόμα και όταν το κάδρο είναι απλό, θέλω να κρατά ρυθμό, αλήθεια και χαρακτήρα.",
      "Με αφετηρία την Αθήνα και διάθεση για επιλεγμένες συνεργασίες.",
    ],
    contactTitle1: "Επικοινώνησε",
    contactTitle2: "Εδώ",
    contactKicker: "",
    contactText:
      "Αν έχεις στο μυαλό σου ένα πορτρέτο, μια ιδέα για brand ή ένα φωτογραφικό project, στείλε μου μήνυμα να το δούμε μαζί.",
    contactEmail: "vayiavs95@gmail.com",
    formName: "ΟΝΟΜΑ",
    formNamePlaceholder: "Το όνομά σου",
    formEmail: "EMAIL",
    formEmailPlaceholder: "το@email σου",
    formInquiryType: "ΤΥΠΟΣ",
    formInquiryOptions: ["Πορτρέτο", "Brand ή προϊον", "Δημιουργικο project"],
    formTimeframe: "ΧΡΟΝΟΣ",
    formTimeframeOptions: ["Ευελικτο", "Μεσα στον μηνα", "Στους επομενους 1-2 μηνες"],
    formBudget: "BUDGET",
    formBudgetOptions: ["Κατω απο €150", "€150-€300", "€300+"],
    formMessage: "ΜΗΝΥΜΑ",
    formMessagePlaceholder: "Πες μου τι έχεις στο μυαλό σου...",
    contactCTA: "Αποστολή",
    contactSending: "Αποστολή...",
    contactSuccess: "Το μήνυμά σου στάλθηκε.",
    contactError: "Κάτι πήγε στραβά. Δοκίμασε ξανά.",
    servicesKicker: "",
    servicesTitle: "",
    servicesLead:
      "Απο προσωπα και brands μεχρι πιο ατμοσφαιρικα δημιουργικα sessions, η καθε συνεργασια χτιζεται με βαση το υφος και την αισθηση που θελεις να κρατησει η εικονα.",
    servicesHeading: "Τροποι συνεργασιας",
    services: [
      {
        title: "Πορτρέτα",
        text: "Πορτρέτα με φυσικό ρυθμό, φωτογραφίσεις για ζευγάρια και προσωπικές λήψεις με ήρεμη, ανεπιτήδευτη κατεύθυνση.",
      },
      {
        title: "Brand & Προϊόν",
        text: "Καθαρές και ατμοσφαιρικές εικόνες για μικρές επιχειρήσεις, personal brands, e-shops και οπτικές καμπάνιες.",
      },
      {
        title: "Δημιουργικά Sessions",
        text: "Συνεργατικές φωτογραφίσεις και visual storytelling με βάση τη διάθεση, το location και την ταυτότητα του project.",
      },
    ],
    offersTitle: "Ενδεικτικος οδηγος",
    offers: [
      {
        label: "Πορτρέτο",
        price: "απο €120",
        meta: "60-90 λεπτα",
      },
      {
        label: "Brand Εικονα",
        price: "απο €180",
        meta: "μικρη επιχειρηση / προϊον",
      },
      {
        label: "Δημιουργικο Project",
        price: "κατοπιν συνεννοησης",
        meta: "concept-based",
      },
    ],
    processTitle: "Πως λειτουργει",
    process: [
      "Μου στελνεις την ιδεα, το mood ή την αναγκη σου.",
      "Οριζουμε κατευθυνση, χρονο και location.",
      "Λαμβανεις καθαρη προσφορα και απλο πλανο.",
      "Η τελικη gallery παραδιδεται με email.",
    ],
    inquire: "Ρώτησέ με",
    portraitCaption: "Ήσυχες στιγμές, αληθινή παρουσία",
    contactMeta: "Αθηνα • επιλεγμενες συνεργασιες • απαντηση με email",
    footerTagline: "Street • Portrait • Atmosphere",
    footerLocation: "Αθηνα, Ελλαδα",
  },
} as const;
