export const siteUrl = "https://vayia-vs-portfolio.vercel.app";

export const curatedImageOrder = [
  "ist8-street.jpg",
  "rome2-archit.png",
  "greece1-landsc.png",
  "skg1-street-int.jpg",
  "ist1-archit-int.png",
  "rome7-street.png",
  "greece3-street.png",
  "ist15-landsc.jpg",
  "rome8-archit-int.png",
  "skg2-street.png",
  "ist10-street.png",
  "rome4-int.png",
  "greece2-landsc.png",
  "ist7-archit.png",
  "rome1-street.png",
  "greece5-street.png",
  "ist9-archit.png",
  "skg3-street.png",
  "rome3-archit-int.png",
  "ist4-street.jpg",
  "greece4-street.png",
  "rome6-archit.png",
  "ist11-street.png",
  "ist2-street.jpg",
  "ist14-street.png",
  "ist5-street.jpg",
  "ist12-street.png",
  "ist3-street.jpg",
  "ist13-street.png",
  "ist6-street.jpg",
  "ist7-street.jpg",
];

export const featuredCategoryOrder: Record<string, string[]> = {
  street: [
    "ist8-street.jpg",
    "rome7-street.png",
    "greece3-street.png",
    "skg1-street-int.jpg",
    "ist10-street.png",
    "greece4-street.png",
    "rome1-street.png",
    "ist4-street.jpg",
  ],
  landsc: [
    "greece1-landsc.png",
    "ist15-landsc.jpg",
    "greece2-landsc.png",
    "greece5-street.png",
  ],
  archit: [
    "rome2-archit.png",
    "ist1-archit-int.png",
    "rome8-archit-int.png",
    "ist7-archit.png",
    "ist9-archit.png",
    "rome3-archit-int.png",
    "rome6-archit.png",
  ],
  int: [
    "rome4-int.png",
    "rome8-archit-int.png",
    "rome3-archit-int.png",
    "ist1-archit-int.png",
    "skg1-street-int.jpg",
  ],
};

export const homeContent = {
  en: {
    nav: [
      { label: "Gallery", target: "gallery" },
      { label: "About", target: "about" },
      { label: "Contact", target: "contact" },
    ],
    heroTitle1: "Capturing",
    heroTitle2: "Moments",
    heroTitle3: "in Time",
    heroText:
      "A curated collection of photographs exploring light, shadow, and the beauty of fleeting moments.",
    viewGallery: "View Gallery",
    contactButton: "Get in Touch",
    galleryTitle: "My Collections",
    showMore: "more...",
    aboutTitle1: "The Art",
    aboutTitle2: "of Seeing",
    aboutKicker: "About the work",
    aboutText: [
      "I photograph the city as it unfolds: small gestures, passing light, and the quiet tension between people and place.",
      "My work moves between street photography, portraiture, architecture, and landscapes, always guided by atmosphere rather than performance.",
      "I am drawn to images that feel intimate and unforced. Even when the frame is simple, I want it to carry rhythm, stillness, and a sense of presence.",
      "Based in Athens and available for selected collaborations.",
    ],
    contactTitle1: "Let's Work",
    contactTitle2: "Together",
    contactKicker: "Get in touch",
    contactText:
      "If you have a role opportunity, a team in need of visual support, or a thoughtful creative collaboration in mind, send me a message.",
    contactEmail: "vayiavs95@gmail.com",
    formName: "Name",
    formNamePlaceholder: "Your name",
    formEmail: "Email",
    formEmailPlaceholder: "your@email.com",
    formInquiryType: "Inquiry Type",
    formInquiryOptions: ["Role opportunity", "Creative collaboration", "General inquiry"],
    formCompany: "Company / Team",
    formCompanyPlaceholder: "Studio, brand, agency, publication...",
    formMessage: "Message",
    formMessagePlaceholder: "Tell me what you have in mind...",
    contactCTA: "Send Message",
    contactSending: "Sending...",
    contactSuccess: "Your message has been sent.",
    contactError: "Something went wrong. Please try again.",
    servicesKicker: "Work with me",
    servicesTitle: "",
    servicesLead: "",
    servicesHeading: "",
    services: [
      {
        title: "Portraits",
        text: "Editorial-feeling portraits, couples sessions, and quiet personal photographs with a natural, relaxed direction.",
      },
      {
        title: "Product Photography",
        text: "Clean, atmospheric imagery for small businesses, personal brands, online shops, and visual campaigns.",
      },
      {
        title: "Street Photography Walks",
        text: "Guided photography walks exploring light, movement, and urban stories together.",
      },
    ],
    inquire: "Inquire",
    portraitCaption: "Quiet moments, honest presence",
    contactMeta: "Athens-based • open to roles and collaborations • replies by email",
    footerTagline: "Street • Portrait • Atmosphere",
    footerLocation: "Athens, Greece",
  },
  gr: {
    nav: [
      { label: "Συλλογές", target: "gallery" },
      { label: "Σχετικά με εμένα", target: "about" },
      { label: "Επικοινωνία", target: "contact" },
    ],
    heroTitle1: "Στιγμές",
    heroTitle2: "που",
    heroTitle3: "μένουν",
    heroText:
      "Μια επιμελημένη επιλογή φωτογραφιών γύρω από το φως, τη σκιά και την ομορφιά των στιγμών που χάνονται γρήγορα.",
    viewGallery: "Περιήγηση",
    contactButton: "Επικοινωνία",
    galleryTitle: "Οι Συλλογές μου",
    showMore: "Περισσοτερα",
    aboutTitle1: "Πίσω",
    aboutTitle2: "από τον φακό",
    aboutKicker: "Σχετικά με εμένα",
    aboutText: [
      "Φωτογραφίζω την πόλη όπως αποκαλύπτεται: μικρές κινήσεις, περαστικό φως και τη σχέση ανάμεσα στους ανθρώπους και τον χώρο.",
      "Η δουλειά μου κινείται ανάμεσα στη φωτογραφία δρόμου, τα πορτρέτα, την αρχιτεκτονική και τα τοπία, με βάση πάντα την ατμόσφαιρα και όχι τη σκηνοθεσία.",
      "Με ενδιαφέρουν οι εικόνες που νιώθουν ήσυχες αλλά παρούσες. Ακόμα και όταν το κάδρο είναι απλό, θέλω να κρατά ρυθμό, αλήθεια και χαρακτήρα.",
      "Με αφετηρία την Αθήνα και διάθεση για επιλεγμένες συνεργασίες.",
    ],
    contactTitle1: "Επικοινώνησε",
    contactTitle2: "Εδώ",
    contactKicker: "",
    contactText:
      "Αν υπάρχει μια επαγγελματική ευκαιρία, μια ομάδα που χρειάζεται visual support ή μια συνεργασία με ουσία, στείλε μου μήνυμα.",
    contactEmail: "vayiavs95@gmail.com",
    formName: "ΟΝΟΜΑ",
    formNamePlaceholder: "Το όνομά σου",
    formEmail: "EMAIL",
    formEmailPlaceholder: "το@email σου",
    formInquiryType: "ΤΥΠΟΣ",
    formInquiryOptions: ["Επαγγελματικη ευκαιρια", "Δημιουργικη συνεργασια", "Γενικη επικοινωνια"],
    formCompany: "ΕΤΑΙΡΕΙΑ / ΟΜΑΔΑ",
    formCompanyPlaceholder: "Studio, brand, agency, publication...",
    formMessage: "ΜΗΝΥΜΑ",
    formMessagePlaceholder: "Πες μου τι έχεις στο μυαλό σου...",
    contactCTA: "Αποστολή",
    contactSending: "Αποστολή...",
    contactSuccess: "Το μήνυμά σου στάλθηκε.",
    contactError: "Κάτι πήγε στραβά. Δοκίμασε ξανά.",
    servicesKicker: "",
    servicesTitle: "",
    servicesLead: "",
    servicesHeading: "",
    services: [
      {
        title: "Πορτρέτα",
        text: "Πορτρέτα με φυσικό ρυθμό, φωτογραφίσεις για ζευγάρια και προσωπικές λήψεις με ήρεμη, ανεπιτήδευτη κατεύθυνση.",
      },
      {
        title: "Φωτογράφιση Προϊόντων",
        text: "Καθαρές και ατμοσφαιρικές εικόνες για μικρές επιχειρήσεις, personal brands, e-shops και οπτικές καμπάνιες.",
      },
      {
        title: "Φωτογραφικές Βόλτες",
        text: "Συνεργατικές βόλτες φωτογραφίας με έμφαση στο φως, την κίνηση και την παρατήρηση της πόλης.",
      },
    ],
    inquire: "Ρώτησέ με",
    portraitCaption: "Ήσυχες στιγμές, αληθινή παρουσία",
    contactMeta: "Αθηνα • ανοιχτη σε ρολους και συνεργασιες • απαντηση με email",
    footerTagline: "Street • Portrait • Atmosphere",
    footerLocation: "Αθηνα, Ελλαδα",
  },
} as const;
